apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenosize-redis
  labels:
    app: redis
spec:
  serviceName: 'redis-svc'
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          ports:
            - containerPort: 6379
              name: redis
